### ISSUE TITLE
O-table: o-table-column nowrap (add class to a column)

### ISSUE THREAD

**Issue by mohamed-benkhalifa** [OntimizeWeb/ontimize-web-ng2#102]
For example:
o-table-column has a css propriety  /* white-space: nowrap; */ which does not show all the column, it is possible to add an attribute to o-table-column where can add a css class, example:  white-space: normal;

**Comment by gonzalo-martinez-imt** [comment]
attribute class in o-column exists in ontimize-web-ng2@2.0.0-rc.4
