### ISSUE TITLE
Table :: Configuration parameters for 'click' events

### ISSUE THREAD

**Issue by daniel-grana** [OntimizeWeb/ontimize-web-ng2#2]
Add configuration parameters for 'click' events:

- 'on-click' -> navigate to detail or just select row.
- 'on-dbl-click' -> open floating detail form or navigate to detail.

**Comment by gonzalo-martinez-imt** [comment]
Already existing feature using 'detail-mode' parameter with values:
  'click'  -> navigate to detail on click
  'doubleclick'  -> navigate to detail on double click
  'none' -> just select row (default value)
Click and doubleclick events are always emmited
