### ISSUE TITLE
Table :: Configuration parameter for navigate detail mode

### ISSUE THREAD

**Issue by daniel-grana** [OntimizeWeb/ontimize-web-ng2#3]
Add a parameter that automatically adds a "chevron" or "pencil" icon to the end of the row that allows the user navigates to detail form.

**Comment by daniel-grana** [comment]
By default:
 - (VISIBLE) 'Magnify glass' icon on the right of each row for showing detail form (opened in 'read only' mode).
 - (HIDDEN) 'Pencil' icon on the left of previous one, for opening detail form on edition mode.

**Comment by gonzalo-martinez-imt** [comment]
Solved
